### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by awesomebytes** [Capsize-Games/airunner#16]
**Describe the bug**
When trying to run from source (in a docker environment with ubuntu 22.04, which I'll share shortly) seems like aihandler is missing to declare a dependency on diffusers as I get the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 1162, in generator_sample
    self._generate(data, image_var=image_var)
  File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 1077, in _generate
    self._initialize()
  File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 636, in _initialize
    self._load_model()
  File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 486, in _load_model
    "scheduler": self.scheduler,
  File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 166, in scheduler
    import diffusers
ModuleNotFoundError: No module named 'diffusers'
```

**To Reproduce**
TODO

**Expected behavior**
Use the app normally :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 running a docker with ubuntu 22.04
 - Version main branch

**Comment by awesomebytes** [comment]
After installing `pip install diffusers` I got:
```
StableDiffusionPipeline requires the transformers library but it was not found in your environment. You can install it with pip: `pip
install transformers

```

**Comment by awesomebytes** [comment]
After installing transformers, I added my huggingface token (is it mandatory?) and clicked generate... waited a while to download the models, and... got my first image generated!

![Screenshot from 2023-04-01 22-26-29](https://user-images.githubusercontent.com/1721716/229286020-407a358b-8a48-451f-9f00-4cda6536ab5a.png)

**Comment by w4ffl35** [comment]
unfortunately diffusers and transformers must be installed separately as outlined here:

https://github.com/Capsize-Games/airunner#prerequisites

you should use these patched versions if you want to use all samplers with ckpt and safetensor files.

**Comment by w4ffl35** [comment]
> **Describe the bug** When trying to run from source (in a docker environment with ubuntu 22.04, which I'll share shortly) seems like aihandler is missing to declare a dependency on diffusers as I get the error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 1162, in generator_sample
>     self._generate(data, image_var=image_var)
>   File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 1077, in _generate
>     self._initialize()
>   File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 636, in _initialize
>     self._load_model()
>   File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 486, in _load_model
>     "scheduler": self.scheduler,
>   File "/usr/local/lib/python3.10/dist-packages/aihandler/runner.py", line 166, in scheduler
>     import diffusers
> ModuleNotFoundError: No module named 'diffusers'
> ```
> 
> **To Reproduce** TODO
> 
> **Expected behavior** Use the app normally :)
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Ubuntu 20.04 running a docker with ubuntu 22.04
> 
>     * Version main branch

unfortunately diffusers and transformers must be installed separately as outlined here:

https://github.com/Capsize-Games/airunner#prerequisites

you should use these patched versions if you want to use all samplers with ckpt and safetensor files.

**Comment by w4ffl35** [comment]
i think i'll add both requirements and then allow people to use the patched versions if they desire.

**Comment by w4ffl35** [comment]
I am closing this issue and keeping the other one open for now.
