### ISSUE TITLE
Program crashed after installing lora, and also deleted my AI model

### ISSUE THREAD

**Issue by SynapticBytes** [Capsize-Games/airunner#163]
**Describe the bug**
I downloaded the Stable Diffusion 1.4 model and put it in a completely separate directory to AI runner. Did a couple of generations, then installed the Lora extension.

Next time I tried to start AI runner, it would run through the startup script, but die before the program launched. I was not able to capture the console log when it was dying, but I did see an orange square drawn around a segment of code before it died.

After multiple attempts at removing the AI Runner directory, and manually cleaning up any files I could fine under C:\User, I finally managed to get AI runner started again. 

I am running on Windows 10, running AI Runner from one of my secondary NVME drives.

**Comment by w4ffl35** [comment]
I believe this is fixed with the latest versions - closing for now. Please comment if you see the same issue on v1.14.2
