### ISSUE TITLE
Version 1.14.0 Windows - not starting

### ISSUE THREAD

**Issue by QaDoPL** [Capsize-Games/airunner#210]
At starting loaders:
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton.language'

Then:

WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:490                                                                                  │
│                                                                                                  │
│ in __init__:157                                                                                  │
│                                                                                                  │
│ in initialize:231                                                                                │
│                                                                                                  │
│ in initialize:249                                                                                │
│                                                                                                  │
│ in initialize_lora:29                                                                            │
│                                                                                                  │
│ in refresh_lora:40                                                                               │
│                                                                                                  │
│ in initialize_lora_trigger_words:132                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'enabledCheckbox'
[57824] Failed to execute script 'main' due to unhandled exception!
[57824] LOADER: OK.
[57824] LOADER: Manually flushing stdout and stderr
[57824] LOADER: Cleaning up Python interpreter.

**Comment by w4ffl35** [comment]
I just saw this - thanks for opening the bug. Fix going live now
