### ISSUE TITLE
Layer color

### ISSUE THREAD

**Issue by w4ffl35** [Capsize-Games/airunner#33]
The green layer color is ugly. Additionally the text is hard to see when the layer is selected.

**Comment by GitCodeBoi1654** [comment]
@w4ffl35 which file is that in

**Comment by w4ffl35** [comment]
> @w4ffl35 which file is that in

https://github.com/Capsize-Games/airunner/blob/master/src/airunner/main.py#L501

The layer template is here, its very basic:

https://github.com/Capsize-Games/airunner/blob/master/src/airunner/pyqt/layer.ui

If you decide to play around with the templates [i highly recommend using PyQT6 Designer](https://stackoverflow.com/questions/66309726/where-is-the-qtdesigner-in-pyqt6)

**Comment by GitCodeBoi1654** [comment]
i got this nice medium cobalt goin on

**Comment by GitCodeBoi1654** [comment]
done and dusted pull request submitted, added light cobalt color

**Comment by GitCodeBoi1654** [comment]
yiu can delete this now i think'

**Comment by GitCodeBoi1654** [comment]
why is it reopened lol

**Comment by GitCodeBoi1654** [comment]
Are u doin the dynamic Color thing where u can change theme

**Comment by w4ffl35** [comment]
I had to remove the code because it had a syntax error, but yes I am planning to allow modifications of colors in preferences eventually
